openapi: 3.0.0
info:
  title: "Flagd Hub API"
  description: "API for managing feature flags."
  version: "1.0.0"
servers:
  - url: "http://localhost:8080/flagd-hub"
tags:
  - name: flagd-hub
    description: API for get/modify feature flags
  - name: flagd-configuration
    description: Exposes the flags.json file for flagd server
paths:
  /flagd/flags:
    get:
      summary: "Get all feature flags"
      description: "Retrieve a list of all feature flags."
      tags:
        - flagd-configuration
      responses:
        200:
          description: "A list of feature flags."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/FeatureFlag"
  /flagd-hub/flags:
    get:
      summary: "Get all feature flags"
      description: "Retrieve a list of all feature flags."
      tags:
        - flags-hub
      responses:
        200:
          description: "A list of feature flags."
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/FeatureFlag"
    post:
      summary: "Create or update a feature flag"
      description: "Create a new feature flag or override an existing one."
      tags:
        - flags-hub
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/FeatureFlag"
      responses:
        200:
          description: "Flag created or updated successfully."
        400:
          description: "Invalid input."
  /flagd-hub/flags/{flagKey}:
    get:
      summary: "Get a specific feature flag"
      description: "Retrieve details of a specific feature flag by its key."
      tags:
        - flags-hub
      parameters:
        - name: "flagKey"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        200:
          description: "Details of the feature flag."
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/FeatureFlag"
        404:
          description: "Flag not found."
    delete:
      summary: "Delete a feature flag"
      description: "Remove a feature flag by its key."
      tags:
        - flags-hub
      parameters:
        - name: "flagKey"
          in: "path"
          required: true
          schema:
            type: "string"
      responses:
        204:
          description: "Flag deleted successfully."
        404:
          description: "Flag not found."
    put:
      summary: "Update a feature flag value"
      description: "Update the default variant of an existing feature flag by its key."
      tags:
        - flags-hub
      parameters:
        - name: "flagKey"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "string"
              description: "The new default variant of the flag."
      responses:
        200:
          description: "Flag value updated successfully."
        400:
          description: "Invalid input."
        404:
          description: "Flag not found."
components:
  schemas:
    FeatureFlag:
      type: "object"
      required:
        - "id"
        - "name"
        - "area"
        - "description"
        - "type"
        - "variants"
        - "defaultVariant"
      properties:
        id:
          type: "string"
          description: "The unique identifier for the flag."
        name:
          type: "string"
          description: "The name of the flag"
        area:
          type: "string"
          description: "The name of the area this flag belongs to"
        description:
          type: "string"
          description: "flag description"
        type:
          type: "string"
          enum: ["boolean", "string", "integer", "float", "object"]
          description: "The type of the flag."
        variants:
          type: object
          additionalProperties:
            type: string
        defaultVariant:
          type: "string"
          description: "The chosen variant of the flag."
    FlagDFeatureFlag:
      type: "object"
      required:
        - "key"
        - "type"
        - "variants"
        - "defaultValue"
      properties:
        key:
          type: "string"
          description: "The unique identifier for the flag."
        type:
          type: "string"
          enum: ["boolean", "string", "integer", "float", "object"]
          description: "The type of the flag."
        variants:
          type: object
          additionalProperties:
            type: string
        defaultValue:
          type: "string"
          description: "The default variant of the flag."
